import argparse
import os
import json
import datetime
import numpy as np
import utils


def parse_args():
    # Create the command-line argument parser
    parser = argparse.ArgumentParser(description='Multi-Subject NIA Encoder Training')

    # Path-related arguments
    parser.add_argument('--model_name', type=str, default='nia_encoder_multisubj_training',
                        help='name of model, used for ckpt saving')
    parser.add_argument('--data_path', type=str, required=True, help='path to where NSD webdataset data is stored')
    parser.add_argument('--clip_model_path', type=str, required=True, help='path to pre-trained CLIP model')
    parser.add_argument('--softroi_root', type=str, required=True,
                        help='path to pre-processed soft-roi data generated by build_softroi_all_subjects.py')
    parser.add_argument('--roi_root', type=str, required=True,
                        help='path to original roi data containing nsdgeneral.nii.gz for each subject')
    parser.add_argument('--model_save_path', type=str, default='', help='path to save results')

    # Data and training arguments
    parser.add_argument('--subjects', type=lambda s: [int(item) for item in s.split(',')], default=[1, 2, 5, 7],
                        help='comma separated list of subjects to train on, e.g., "1,2,5,7"')
    parser.add_argument('--batch_size', type=int, default=16, help='batch size PER GPU for training')
    parser.add_argument('--num_epochs', type=int, default=180, help='number of epochs of training')
    parser.add_argument('--seed', type=int, default=42)
    parser.add_argument('--resume', type=str, default='', help='path to checkpoint to resume training')
    parser.add_argument('--max_lr', type=float, default=3e-4)
    parser.add_argument('--recon_loss', type=str, default='charb',
                        choices=['mse', 'l1', 'huber', 'quantile', 'charb'])
    parser.add_argument('--use_image_aug', action=argparse.BooleanOptionalAction, default=True,
                        help='whether to use image augmentation')
    parser.add_argument('--plot_umap', action=argparse.BooleanOptionalAction, default=True, help='plot UMAP plots')
    parser.add_argument('--lr_scheduler_type', type=str, default='cycle', choices=['cycle', 'linear'])
    parser.add_argument('--ckpt_interval', type=int, default=5, help='save backup ckpt and reconstruct every x epochs')
    parser.add_argument('--ckpt_saving', action=argparse.BooleanOptionalAction, default=True)
    parser.add_argument('--save_at_end', action=argparse.BooleanOptionalAction, default=False,
                        help='if True, saves best.ckpt at end of training.')
    parser.add_argument('--save_last', action=argparse.BooleanOptionalAction, default=False,
                        help='Save last.pth at intervals and at the end when enabled')

    # Model architecture arguments
    parser.add_argument('--atlas_names', type=lambda s: [item.strip() for item in s.split(',')],
                        default='HCP_MMP1,Kastner2015', help='comma separated list of atlas names to use')
    parser.add_argument('--feat_dim', type=int, help='feature: 1024 (ViT) or 4096 (LLM)', default=1024)
    parser.add_argument('--num_latents', type=int, default=256,
                        help='Number of latent tokens for PerceiverResampler output')

    # NIA-specific arguments
    parser.add_argument('--coord_norm', type=str, default='unit', choices=['none', 'unit', 'mm'],
                        help="Coordinate normalization mode before RFF.")
    parser.add_argument('--attn_scale', type=str, default='sqrt', choices=['none', 'sqrt'],
                        help="Attention logit scaling (divide by sqrt(rank)).")
    parser.add_argument('--attn_norm', type=str, default='layernorm', choices=['none', 'layernorm', 'rmsnorm'],
                        help="Normalization applied to Q/K in attention.")
    parser.add_argument('--attn_tau_init', type=float, default=1.0,
                        help="Initial value for attention temperature tau.")
    parser.add_argument('--attn_tau_learnable', action=argparse.BooleanOptionalAction, default=False,
                        help="Whether the attention temperature is a learnable parameter.")
    parser.add_argument('--attn_dropout', type=float, default=0.5,
                        help="Target dropout rate after the attention layer.")
    parser.add_argument('--ffn_dropout', type=float, default=0.15,
                        help="Target dropout rate in the FFN blocks.")
    parser.add_argument('--dropout_warm_epochs', type=int, default=3,
                        help="Number of epochs to warm up dropout rate linearly. 0 to disable.")
    parser.add_argument('--fusion_mode', type=str, default='concat', choices=['concat', 'gate', 'gate_voxel'],
                        help='how to fuse features from multiple atlases')
    parser.add_argument('--gate_voxel_proj_dim', type=int, default=64,
                        help="Projection dimension for gate_voxel mode to save memory.")

    args = parser.parse_args()

    # Handle the case where atlas_names is a string by default, so it will not be incorrectly iterated character by character later
    if isinstance(args.atlas_names, str):
        args.atlas_names = [item.strip() for item in args.atlas_names.split(',')]

    return args


def setup_run(args, accelerator):
    """Create the experiment output directory, save the configuration, and set the random seed."""
    subjects_str = "".join(map(str, args.subjects))

    # If the user explicitly provides an output path, use it directly;
    # otherwise, generate one automatically based on the date and settings
    if args.model_save_path:
        outdir = args.model_save_path
    else:
        date = datetime.datetime.now().strftime("%y%m%d")
        outdir = os.path.abspath(f'./train_logs/{args.model_name}_{date}/sub{subjects_str}_dim{args.feat_dim}')

    # Only the main process creates the directory and writes the config file to avoid conflicts in multi-process training
    if accelerator.is_main_process:
        os.makedirs(outdir, exist_ok=True)
        with open(os.path.join(outdir, 'config.json'), 'w') as file:
            json.dump(vars(args), file, indent=4)

    # Wait for all processes to synchronize before continuing
    accelerator.wait_for_everyone()

    # Set the random seed to improve reproducibility
    utils.seed_everything(args.seed, cudnn_deterministic=False)

    return outdir